# Site settings
title: Yeongdo Bridge
email: help@yeongdobirdge.org
description: > # this means to ignore newlines until "baseurl:"
  hello
baseurl: "" 
url: "http://yeongdobridge.org" 
github_username: yeongdo

# Build settings
markdown: kramdown
